# Generated by Django 3.1.4 on 2020-12-09 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=256, verbose_name='First Name')),
                ('mname', models.CharField(blank=True, max_length=256, null=True, verbose_name='Middle Name')),
                ('lname', models.CharField(max_length=256, verbose_name='Last Name')),
                ('ename', models.CharField(blank=True, choices=[('JR', 'JR'), ('SR', 'SR'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=4, null=True, verbose_name='Suffix')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('birthdate', models.DateField(verbose_name='Date of Birth')),
                ('mobile1', models.CharField(max_length=11, verbose_name='Primary Mobile No.')),
                ('mobile1_confirmed', models.BooleanField(default=False)),
                ('mobile2', models.CharField(blank=True, max_length=11, null=True, verbose_name='Alternative Mobile No.')),
                ('mobile2_confirmed', models.BooleanField(default=False)),
                ('current_street', models.CharField(max_length=256, verbose_name='Current Street Address')),
                ('current_town', models.CharField(max_length=256, verbose_name='Current Barangay/Town')),
                ('current_city', models.CharField(max_length=256, verbose_name='Current City/Municipality')),
                ('current_region', models.CharField(max_length=256, verbose_name='Current State/Province')),
                ('perm_street', models.CharField(max_length=256, verbose_name='Permanent Street Address')),
                ('perm_town', models.CharField(max_length=256, verbose_name='Permanent Barangay/Town')),
                ('perm_city', models.CharField(max_length=256, verbose_name='Permanent City/Municipality')),
                ('perm_region', models.CharField(max_length=256, verbose_name='Permanent State/Province')),
                ('face_photo', models.ImageField(upload_to='face', verbose_name='Photo')),
                ('id_photo', models.ImageField(upload_to='id', verbose_name='ID Photo')),
                ('qr_code_text', models.CharField(blank=True, max_length=20, verbose_name='QR Code Text')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Time Created')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Time Updated')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Email Address')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
