# Generated by Django 3.1.4 on 2020-12-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracing', '0003_auto_20201210_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishmentprofilemodel',
            name='landline',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Landline No.'),
        ),
    ]
